"""Add missing customer and driver fields

Revision ID: 78458c3d2e29
Revises: 63c9011ec3c6
Create Date: 2026-07-08 12:46:43.258213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78458c3d2e29'
down_revision: Union[str, Sequence[str], None] = '63c9011ec3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('license_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'license_number')
    op.drop_column('customers', 'company_name')
    op.drop_column('customers', 'contact_phone')
    op.drop_column('customers', 'contact_email')
    # ### end Alembic commands ###
